In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from collections import Counter
import warnings
warnings.filterwarnings('ignore')

In [4]:
x = pd.read_csv('data.csv', encoding='latin1')

In [5]:
x.head(5)

,URLs,Headline,Body,Label,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,http://www.bbc.com/news/world-us-canada-414191...,Four ways Bob Corker skewered Donald Trump,Image copyright Getty Images\nOn Sunday mornin...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.reuters.com/article/us-filmfestiva...,Linklater's war veteran comedy speaks to moder...,"LONDON (Reuters) - Last Flag Flying, a comed...",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.nytimes.com/2017/10/09/us/politics...,Trumps Fight With Corker Jeopardizes His Legi...,The feud broke into public view last week when...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.reuters.com/article/us-mexico-oil-...,Egypt's Cheiron wins tie-up with Pemex for Mex...,MEXICO CITY (Reuters) - Egypts Cheiron Holdin...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,http://www.cnn.com/videos/cnnmoney/2017/10/08/...,Jason Aldean opens 'SNL' with Vegas tribute,"Country singer Jason Aldean, who was performin...",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
x.shape

(4141, 12)

In [7]:
x = x[['URLs','Headline','Body','Label']]

In [8]:
x.head(3)

,URLs,Headline,Body,Label
0,http://www.bbc.com/news/world-us-canada-414191...,Four ways Bob Corker skewered Donald Trump,Image copyright Getty Images\nOn Sunday mornin...,1
1,https://www.reuters.com/article/us-filmfestiva...,Linklater's war veteran comedy speaks to moder...,"LONDON (Reuters) - Last Flag Flying, a comed...",1
2,https://www.nytimes.com/2017/10/09/us/politics...,Trumps Fight With Corker Jeopardizes His Legi...,The feud broke into public view last week when...,1

In [9]:
x.isnull().sum()

URLs          0
Headline     50
Body         99
Label       107
dtype: int64

In [10]:
headline_null = x[x['Headline'].isnull()].index.tolist()
print(headline_null)

[438, 444, 445, 446, 449, 450, 455, 459, 468, 477, 479, 484, 485, 486, 489, 490, 498, 502, 503, 510, 512, 513, 515, 516, 519, 520, 522, 523, 525, 526, 528, 531, 532, 534, 535, 537, 538, 539, 540, 2112, 2321, 2322, 2323, 2329, 2331, 2335, 2338, 2340, 2341, 2343]

In [11]:
m = x['Headline'].mode()[0]
m

"10/1 Expo Park-Forbes Field Era: Deacon Whips Cy In 1st WS Game, Waner's 237 Hits, Boss Man Roberto & More"

In [12]:
x['Headline'].iloc[headline_null] = m

In [13]:
x.isnull().sum()

URLs          0
Headline      0
Body         99
Label       107
dtype: int64

In [14]:
body_null = x[x['Body'].isnull()].index.tolist()
print(body_null)

[247, 269, 325, 395, 436, 437, 438, 442, 444, 445, 446, 447, 449, 450, 451, 454, 455, 459, 466, 467, 468, 473, 477, 479, 481, 483, 484, 485, 486, 489, 490, 496, 498, 500, 502, 503, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 525, 526, 527, 528, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 613, 986, 1077, 1085, 1110, 1237, 1314, 1604, 1889, 2111, 2112, 2113, 2321, 2322, 2323, 2329, 2331, 2334, 2335, 2337, 2338, 2340, 2341, 2343, 2345, 2386, 2434, 2841, 3091, 3240, 3448, 3509, 4138]

In [15]:
m = x['Body'].mode()[0]
m

'A Potato Battery Can Light up a Room for Over a Month DIY (System That Can Be Used to Provide Rooms With LED-Powered Lighting for as Long as 40 days) +Video'

In [16]:
x['Body'].iloc[body_null] = m

In [17]:
x.isnull().sum()

URLs          0
Headline      0
Body          0
Label       107
dtype: int64

In [18]:
label_null = x[x['Label'].isnull()].index.tolist()
print(label_null)

[436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 457, 459, 460, 462, 463, 464, 465, 466, 467, 468, 473, 476, 477, 478, 479, 481, 482, 483, 484, 485, 486, 489, 490, 491, 493, 495, 496, 498, 499, 500, 502, 503, 506, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 2111, 2112, 2113, 2320, 2321, 2322, 2323, 2324, 2329, 2330, 2331, 2334, 2335, 2337, 2338, 2339, 2340, 2341, 2343, 2345, 2347]

In [19]:
# before proceding with model building lets fill the missing values
Counter(x['Label'])

Counter({'1': 1870,
         '0': 2133,
         ' she said. He will be missed by all who knew him': 1,
         nan: 107,
         ' police said.': 1,
         ' the department said.': 1,
         ' died holding the hand of a stranger at the concert.': 1,
         ' Colorado.': 1,
         ' Colorado. He was known there for his ""big teddy bear smile and infectious laughter': 1,
         ' friend and hero': 1,
         ' sweet': 1,
         ' he wrote.': 1,
         ' the excitement faded': 1,
         ' California': 1,
         ' Vinnie Etcheber told his wife to run as he began to render aid to those wounded': 1,
         ' mother': 1,
         ' 50': 1,
         ' Denise Burditus posted a picture of the two standing in front of the Route 91 Harvest stage.': 1,
         ' he wrote on Facebook. ""Denise passed in my arms. I LOVE YOU BABE.""': 1,
         ' Derwent Innovations Index': 1,
         ' as indexed in the Clarivate Analytics Web of Science Core Collection database. The list was cross-referenced against the number of patents filed by each organization during the same time period in the Derwent World Patents Index and the Derwent Innovations Index. Patent equivalents': 1,
         ' it may not be possible to identify which of the various campuses was responsible for the initial research': 1,
         ' since that indicator is closely related to demonstrating the continuing utility of an invention or process."': 1,
         ' speakers that face the user and an \x93active edge\x94 allowing users \x85': 1,
         ' \x93WTF With Marc Maron': 1,
         ' relationships': 1,
         ' is to home in on regional gastronomical creations.': 1,
         ' they are indigenous': 1,
         ' so you get it for breakfast; corned beef and eggs': 1,
         ' but I wanted to find real Brunswick stew. It\x92s like something you get in hot lunch at school. It\x92s like a tomato based stew': 1,
         ' you\x92re just going to have to suck it up.': 1,
         ' you don\x92t know what that chair\x92s been through. You don\x92t know what\x92s been done on that chair': 1,
         ' so you don\x92t really see the size of my duffel bag. I\x92ve carried on like two weeks worth of stuff': 1,
         ' that New York has to offer in any real way. I was very focused on my work. So': 1})

In [20]:
x['Label'].fillna(0, inplace = True)

In [21]:
x.isnull().sum()

URLs        0
Headline    0
Body        0
Label       0
dtype: int64

# 2nd file

In [22]:
y = pd.read_csv('fake_new_dataset.csv', encoding='latin1')
y.head(2)

,Unnamed: 0,title,text,subcategory,label
0,0,FACEBOOK DELETES MICHIGAN ANTI-LOCKDOWN GROUP ...,Facebook has shuttered a popular group for Mic...,false news,0
1,1,Other Viewpoints: COVID-19 is worse than the flu,We can now officially put to rest all comparis...,true,1

In [23]:
y = pd.read_csv('fake_new_dataset.csv', index_col=0, encoding='latin1')

In [24]:
y.head(5)

,title,text,subcategory,label
0,FACEBOOK DELETES MICHIGAN ANTI-LOCKDOWN GROUP ...,Facebook has shuttered a popular group for Mic...,false news,0
1,Other Viewpoints: COVID-19 is worse than the flu,We can now officially put to rest all comparis...,true,1
2,Bermuda's COVID-19 cases surpass 100,The Ministry of Health in Bermuda has confirme...,true,1
3,Purdue University says students face 'close to...,"Purdue University President Mitch Daniels, the...",partially false,0
4,THE HIGH COST OF LOCKING DOWN AMERICA: WEVE ...,Locking down much of the country may have help...,false news,0

In [25]:
y.isnull().sum()

title          1
text           0
subcategory    0
label          0
dtype: int64

In [26]:
y.shape

(3119, 4)

In [27]:
y['title'] = y['title'].fillna(y['title'].mode()[0])

In [28]:
y.isnull().sum()

title          0
text           0
subcategory    0
label          0
dtype: int64

In [29]:
Counter(y['subcategory'])

Counter({'false news': 659, 'true': 2061, 'partially false': 399})

In [30]:
Counter(y['label'])

Counter({0: 1058, 1: 2061})

# 3rd file

In [31]:
z = pd.read_csv('FakeNewsNet.csv', encoding='latin1')

In [32]:
z.head(3)

,title,news_url,source_domain,tweet_num,real
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1

In [33]:
z.shape

(23196, 5)

In [34]:
z.isnull().sum()

title              0
news_url         330
source_domain    330
tweet_num          0
real               0
dtype: int64

In [35]:
news_url_null = z[z['news_url'].isnull()].index.tolist()
print(news_url_null)

[14, 72, 87, 177, 198, 221, 230, 248, 272, 283, 287, 383, 599, 623, 625, 632, 803, 835, 847, 900, 963, 1063, 1111, 1365, 1524, 1551, 1583, 1633, 1642, 1705, 1748, 1842, 1849, 1855, 1945, 1981, 1995, 2004, 2081, 2176, 2208, 2280, 2439, 2461, 2466, 2536, 2559, 2796, 2822, 2863, 2947, 2995, 3088, 3454, 3458, 3559, 3603, 3636, 3913, 3918, 4103, 4135, 4195, 4255, 4302, 4345, 4447, 4504, 4538, 4552, 4611, 4872, 4946, 5033, 5045, 5208, 5324, 5383, 5432, 5461, 5506, 5605, 5640, 5687, 5740, 5754, 5799, 5945, 6156, 6208, 6223, 6306, 6372, 6399, 6405, 6441, 6597, 6626, 6748, 7057, 7242, 7421, 7426, 7664, 7739, 7754, 7825, 7843, 7880, 7921, 8242, 8380, 8415, 8456, 8561, 8607, 8617, 9047, 9074, 9230, 9297, 9373, 9432, 9474, 9520, 9569, 9618, 9637, 9665, 9700, 9873, 10045, 10079, 10134, 10142, 10252, 10266, 10277, 10305, 10364, 10408, 10728, 10729, 10746, 10762, 10800, 10822, 10876, 10893, 10953, 10954, 11001, 11062, 11201, 11244, 11277, 11291, 11305, 11359, 11396, 11686, 11706, 11758, 11860, 11918, 11940, 11991, 12049, 12118, 12168, 12230, 12281, 12313, 12324, 12421, 12502, 12591, 12613, 12629, 12641, 12680, 12882, 12930, 12960, 13059, 13267, 13317, 13365, 13444, 13525, 13531, 13576, 13616, 13816, 14044, 14218, 14255, 14287, 14372, 14377, 14635, 14678, 14763, 14815, 14842, 14903, 14976, 15097, 15233, 15282, 15412, 15451, 15544, 15662, 15889, 16111, 16178, 16189, 16223, 16337, 16514, 16573, 16604, 16663, 16678, 16733, 16805, 16822, 16846, 16850, 17036, 17059, 17072, 17098, 17216, 17232, 17248, 17339, 17345, 17347, 17448, 17531, 17607, 17663, 17681, 17692, 17716, 17822, 17833, 17877, 17891, 17896, 18035, 18161, 18238, 18270, 18297, 18360, 18413, 18626, 18681, 18706, 18708, 18729, 18866, 18896, 18976, 19015, 19180, 19285, 19322, 19326, 19395, 19426, 19432, 19437, 19492, 19493, 19562, 19575, 19651, 19769, 19778, 19931, 19951, 19955, 19980, 20053, 20080, 20090, 20151, 20285, 20287, 20419, 20427, 20564, 20654, 20665, 20715, 20851, 20859, 20924, 21050, 21075, 21206, 21257, 21280, 21479, 21781, 21787, 21837, 21866, 22068, 22101, 22188, 22268, 22310, 22485, 22513, 22543, 22558, 22566, 22620, 22697, 22810, 22915, 22997, 23011, 23102, 23152]

In [36]:
m = z['news_url'].mode()[0]       # Here we findout 1st mode of this coulmn
m

'https://www.thewrap.com/this-is-us-everything-we-know-her-rebecca-future-randall-tess-beth-mother/'

In [37]:
z['news_url'].iloc[news_url_null] = m

In [38]:
z.isnull().sum()

title              0
news_url           0
source_domain    330
tweet_num          0
real               0
dtype: int64

In [39]:
source_domain_null = z[z['source_domain'].isnull()].index.tolist()
print(source_domain_null)

[14, 72, 87, 177, 198, 221, 230, 248, 272, 283, 287, 383, 599, 623, 625, 632, 803, 835, 847, 900, 963, 1063, 1111, 1365, 1524, 1551, 1583, 1633, 1642, 1705, 1748, 1842, 1849, 1855, 1945, 1981, 1995, 2004, 2081, 2176, 2208, 2280, 2439, 2461, 2466, 2536, 2559, 2796, 2822, 2863, 2947, 2995, 3088, 3454, 3458, 3559, 3603, 3636, 3913, 3918, 4103, 4135, 4195, 4255, 4302, 4345, 4447, 4504, 4538, 4552, 4611, 4872, 4946, 5033, 5045, 5208, 5324, 5383, 5432, 5461, 5506, 5605, 5640, 5687, 5740, 5754, 5799, 5945, 6156, 6208, 6223, 6306, 6372, 6399, 6405, 6441, 6597, 6626, 6748, 7057, 7242, 7421, 7426, 7664, 7739, 7754, 7825, 7843, 7880, 7921, 8242, 8380, 8415, 8456, 8561, 8607, 8617, 9047, 9074, 9230, 9297, 9373, 9432, 9474, 9520, 9569, 9618, 9637, 9665, 9700, 9873, 10045, 10079, 10134, 10142, 10252, 10266, 10277, 10305, 10364, 10408, 10728, 10729, 10746, 10762, 10800, 10822, 10876, 10893, 10953, 10954, 11001, 11062, 11201, 11244, 11277, 11291, 11305, 11359, 11396, 11686, 11706, 11758, 11860, 11918, 11940, 11991, 12049, 12118, 12168, 12230, 12281, 12313, 12324, 12421, 12502, 12591, 12613, 12629, 12641, 12680, 12882, 12930, 12960, 13059, 13267, 13317, 13365, 13444, 13525, 13531, 13576, 13616, 13816, 14044, 14218, 14255, 14287, 14372, 14377, 14635, 14678, 14763, 14815, 14842, 14903, 14976, 15097, 15233, 15282, 15412, 15451, 15544, 15662, 15889, 16111, 16178, 16189, 16223, 16337, 16514, 16573, 16604, 16663, 16678, 16733, 16805, 16822, 16846, 16850, 17036, 17059, 17072, 17098, 17216, 17232, 17248, 17339, 17345, 17347, 17448, 17531, 17607, 17663, 17681, 17692, 17716, 17822, 17833, 17877, 17891, 17896, 18035, 18161, 18238, 18270, 18297, 18360, 18413, 18626, 18681, 18706, 18708, 18729, 18866, 18896, 18976, 19015, 19180, 19285, 19322, 19326, 19395, 19426, 19432, 19437, 19492, 19493, 19562, 19575, 19651, 19769, 19778, 19931, 19951, 19955, 19980, 20053, 20080, 20090, 20151, 20285, 20287, 20419, 20427, 20564, 20654, 20665, 20715, 20851, 20859, 20924, 21050, 21075, 21206, 21257, 21280, 21479, 21781, 21787, 21837, 21866, 22068, 22101, 22188, 22268, 22310, 22485, 22513, 22543, 22558, 22566, 22620, 22697, 22810, 22915, 22997, 23011, 23102, 23152]

In [40]:
m = z['source_domain'].mode()[0]       # Here we findout 1st mode of this coulmn
m

'people.com'

In [41]:
z['source_domain'].iloc[source_domain_null] = m

In [42]:
z.isnull().sum()

title            0
news_url         0
source_domain    0
tweet_num        0
real             0
dtype: int64

In [43]:
z.rename(columns={"real": "label"}, inplace=True)
z.head()

,title,news_url,source_domain,tweet_num,label
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20,1
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38,1

# 4th file

In [44]:
a = pd.read_csv('submission_real_file.csv', encoding='latin1')

In [45]:
a.head(5)

   id  real_id
0   0        2
1   1        2
2   2        1
3   3        1
4   4        2

In [46]:
a = a[['real_id']]

In [47]:
a.isnull().sum()

real_id    0
dtype: int64

In [48]:
a.head()

   real_id
0        2
1        2
2        1
3        1
4        2

In [49]:
a.shape

(1068, 1)

# 5th file

In [50]:
b = pd.read_csv('WELFake_Dataset.csv', encoding='latin1')

In [51]:
b.head(5)

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMAâS ATTORNEY GENERAL SAYS ...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [52]:
b = pd.read_csv('WELFake_Dataset.csv', index_col = 0, encoding='latin1')
b.head()

,title,text,label
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,NaN,Did they post their votes for Hillary already?,1
2,UNBELIEVABLE! OBAMAâS ATTORNEY GENERAL SAYS ...,"Now, most of the demonstrators gathered last ...",1
3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [53]:
b.isnull().sum()

title    558
text      39
label      0
dtype: int64

In [54]:
b.shape

(72134, 3)

In [55]:
title_null = b[b['title'].isnull()].index.tolist()
print(title_null)

[1, 43, 162, 185, 269, 318, 358, 639, 686, 884, 912, 1008, 1269, 1315, 1321, 1502, 1511, 1539, 1623, 1893, 2199, 2551, 2646, 3242, 3726, 3738, 3995, 4064, 4167, 4262, 4297, 4982, 5191, 5531, 5654, 5798, 5817, 5911, 5954, 6010, 6054, 6116, 6135, 6294, 6634, 6705, 6723, 6839, 6916, 7042, 7081, 7371, 7561, 7727, 7744, 8042, 8105, 8356, 8574, 9244, 9494, 9564, 9644, 9695, 9770, 10366, 10633, 10817, 10939, 11044, 11064, 11313, 11555, 11733, 11794, 11810, 11943, 12051, 12077, 12095, 12393, 12510, 12765, 12868, 12869, 14285, 15020, 15166, 15211, 15293, 15454, 15605, 15648, 15835, 15920, 16126, 16224, 16708, 16956, 17036, 17227, 17415, 17484, 17556, 17701, 17828, 18092, 18142, 18314, 18349, 18596, 18623, 18825, 18904, 19130, 19193, 19258, 19320, 19555, 19606, 19673, 19697, 19953, 20533, 20729, 21076, 21086, 21122, 21192, 21195, 21326, 21511, 21655, 21668, 21690, 21914, 22030, 22243, 22325, 22498, 22595, 22682, 22775, 23110, 23289, 23391, 23484, 23529, 23824, 24017, 24178, 24206, 24269, 24494, 24602, 25143, 25168, 25190, 25270, 25559, 25625, 25629, 25693, 25775, 25808, 25977, 26205, 26273, 26497, 26626, 26645, 26790, 27383, 27398, 27552, 27561, 27573, 27645, 27701, 27853, 27880, 28002, 28217, 28889, 28896, 29058, 29068, 29250, 29330, 29462, 29488, 29499, 29557, 29626, 29680, 30033, 30057, 30167, 30254, 30330, 30482, 30576, 30702, 30922, 30937, 31052, 31095, 31112, 31389, 31477, 31495, 31584, 31816, 31943, 31951, 31961, 32135, 32214, 32431, 32516, 32864, 33074, 33110, 33166, 33167, 33173, 33325, 33333, 33410, 33547, 33682, 33688, 33803, 33891, 33990, 34006, 34138, 34176, 34376, 34404, 34704, 34758, 34866, 34884, 35016, 35269, 35688, 35738, 35803, 35831, 36162, 36352, 36361, 36471, 36492, 36529, 36539, 36726, 36811, 37258, 37320, 37407, 37643, 37677, 37712, 37835, 37902, 38087, 38138, 38538, 38834, 39009, 39135, 39226, 39262, 39428, 39454, 39590, 39632, 40181, 40204, 40233, 40316, 40614, 40868, 41030, 41086, 41093, 41149, 41219, 41228, 41571, 42026, 42052, 42158, 42225, 42248, 42840, 43084, 43320, 43359, 43391, 43522, 43666, 43743, 43865, 44493, 44563, 44581, 44816, 44875, 44938, 44981, 45070, 45174, 45307, 45702, 45716, 45732, 45753, 45762, 46155, 46238, 46287, 46442, 46447, 46485, 46622, 46623, 46701, 46713, 46892, 46995, 47051, 47093, 47226, 47240, 47269, 47346, 47388, 47459, 47712, 47739, 47745, 47945, 48235, 48256, 48402, 48685, 48729, 48987, 49000, 49089, 49190, 49463, 49576, 49615, 49685, 49775, 49856, 49932, 50136, 50204, 50297, 50331, 50561, 50650, 50789, 50868, 51106, 51492, 51533, 51578, 51643, 51649, 51776, 52050, 52165, 52180, 52209, 52386, 52494, 52558, 52809, 52971, 53009, 53116, 53191, 53296, 53304, 53308, 53489, 53491, 53551, 53555, 53685, 53686, 53742, 53799, 53806, 53923, 54026, 54211, 54583, 54824, 54865, 54978, 54979, 55216, 55298, 55378, 55394, 55466, 55577, 55591, 55924, 56034, 56132, 56270, 56282, 56289, 56306, 56319, 56457, 56489, 56588, 56595, 56847, 56938, 56996, 57050, 57215, 57266, 57333, 57334, 57392, 57410, 57517, 57530, 57624, 57775, 57907, 57979, 58056, 58145, 58307, 58534, 58590, 58700, 58710, 58772, 58783, 58897, 59205, 59317, 59657, 59762, 59819, 60076, 60090, 60243, 60267, 60475, 60776, 60863, 60879, 61041, 61283, 61297, 61535, 61558, 61561, 61687, 61876, 62019, 62066, 62669, 62747, 62753, 62764, 62842, 62965, 63031, 63160, 63475, 63619, 63669, 63715, 63898, 63921, 63929, 63988, 64101, 64132, 64196, 64222, 64393, 64518, 64659, 64830, 64860, 65456, 65594, 65680, 65712, 65728, 65782, 66052, 66090, 66277, 66441, 66452, 66495, 66545, 66740, 67123, 67218, 67348, 67368, 67442, 67481, 67518, 67909, 68107, 68240, 68271, 68315, 68359, 68441, 68558, 68660, 68703, 69181, 69212, 69294, 69299, 69391, 69591, 69707, 69792, 70031, 70187, 70229, 70323, 70606, 70635, 70686, 70911, 70951, 71028, 71279, 71379, 71402, 71484, 71521, 71540, 71570, 71734]

In [56]:
m = b['title'].mode()[0]       # Here we findout 1st mode of this coulmn
m

'Factbox: Trump fills top jobs for his administration'

In [57]:
b['title'].iloc[title_null] = m

In [58]:
b.isnull().sum()

title     0
text     39
label     0
dtype: int64

In [59]:
text_null = b[b['text'].isnull()].index.tolist()
print(text_null)

[2457, 3534, 3709, 5612, 6270, 6997, 7083, 8974, 16717, 17781, 18342, 24076, 26324, 26898, 30280, 31711, 35933, 37578, 40241, 44166, 45468, 45714, 46383, 46940, 47751, 48677, 49031, 50212, 53407, 54258, 54264, 56864, 58345, 59272, 59436, 63882, 64832, 65316, 67781]

In [60]:
m = b['text'].mode()      # Here we findout 1st mode of this coulmn
m

0
dtype: object

In [61]:
b['text'].iloc[text_null] = m

In [62]:
b.isnull().sum()

title     0
text     39
label     0
dtype: int64

In [63]:
b['text'].fillna(0, inplace = True)

In [64]:
b.isnull().sum()

title    0
text     0
label    0
dtype: int64

# Check head for merging

In [65]:
x.head(3)

,URLs,Headline,Body,Label
0,http://www.bbc.com/news/world-us-canada-414191...,Four ways Bob Corker skewered Donald Trump,Image copyright Getty Images\nOn Sunday mornin...,1
1,https://www.reuters.com/article/us-filmfestiva...,Linklater's war veteran comedy speaks to moder...,"LONDON (Reuters) - Last Flag Flying, a comed...",1
2,https://www.nytimes.com/2017/10/09/us/politics...,Trumps Fight With Corker Jeopardizes His Legi...,The feud broke into public view last week when...,1

In [66]:
x.shape

(4141, 4)

In [67]:
y.head(3)

,title,text,subcategory,label
0,FACEBOOK DELETES MICHIGAN ANTI-LOCKDOWN GROUP ...,Facebook has shuttered a popular group for Mic...,false news,0
1,Other Viewpoints: COVID-19 is worse than the flu,We can now officially put to rest all comparis...,true,1
2,Bermuda's COVID-19 cases surpass 100,The Ministry of Health in Bermuda has confirme...,true,1

In [68]:
y.shape

(3119, 4)

In [69]:
z.head(3)

,title,news_url,source_domain,tweet_num,label
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1

In [70]:
z.shape

(23196, 5)

In [71]:
b.head(3)

,title,text,label
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,Factbox: Trump fills top jobs for his administ...,Did they post their votes for Hillary already?,1
2,UNBELIEVABLE! OBAMAâS ATTORNEY GENERAL SAYS ...,"Now, most of the demonstrators gathered last ...",1

In [72]:
b.shape

(72134, 3)

# Concat data in one file

In [73]:
y = y[['title', 'text', 'label']]
y.shape

(3119, 3)

In [74]:
# the index is repeating, this has to be taken care
con1 = pd.concat([y,b],axis=0,ignore_index=True)
con1

,title,text,label
0,FACEBOOK DELETES MICHIGAN ANTI-LOCKDOWN GROUP ...,Facebook has shuttered a popular group for Mic...,0
1,Other Viewpoints: COVID-19 is worse than the flu,We can now officially put to rest all comparis...,1
2,Bermuda's COVID-19 cases surpass 100,The Ministry of Health in Bermuda has confirme...,1
3,Purdue University says students face 'close to...,"Purdue University President Mitch Daniels, the...",0
4,THE HIGH COST OF LOCKING DOWN AMERICA: WEVE ...,Locking down much of the country may have help...,0
...,...,...,...
75248,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,0
75249,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n...",1
75250,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,0
75251,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trumpâs comba...,0
75252,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,1

In [75]:
x.rename(columns={"Headline": "title", 'Body': 'text', 'Label': 'label'}, inplace=True)
x.head(3)

,URLs,title,text,label
0,http://www.bbc.com/news/world-us-canada-414191...,Four ways Bob Corker skewered Donald Trump,Image copyright Getty Images\nOn Sunday mornin...,1
1,https://www.reuters.com/article/us-filmfestiva...,Linklater's war veteran comedy speaks to moder...,"LONDON (Reuters) - Last Flag Flying, a comed...",1
2,https://www.nytimes.com/2017/10/09/us/politics...,Trumps Fight With Corker Jeopardizes His Legi...,The feud broke into public view last week when...,1

In [76]:
x = x[['title', 'text', 'label']]

In [77]:
pd.concat([x,con1],axis=0,ignore_index=True)           # Final file with concat method

,title,text,label
0,Four ways Bob Corker skewered Donald Trump,Image copyright Getty Images\nOn Sunday mornin...,1
1,Linklater's war veteran comedy speaks to moder...,"LONDON (Reuters) - Last Flag Flying, a comed...",1
2,Trumps Fight With Corker Jeopardizes His Legi...,The feud broke into public view last week when...,1
3,Egypt's Cheiron wins tie-up with Pemex for Mex...,MEXICO CITY (Reuters) - Egypts Cheiron Holdin...,1
4,Jason Aldean opens 'SNL' with Vegas tribute,"Country singer Jason Aldean, who was performin...",1
...,...,...,...
79389,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,0
79390,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n...",1
79391,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,0
79392,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trumpâs comba...,0
79393,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,1

In [78]:
# Only source domain, tweet num columns file couldn't be concat or merge

# Extra

In [79]:
z.head(3)

,title,news_url,source_domain,tweet_num,label
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1

In [80]:
x.head(3)

,title,text,label
0,Four ways Bob Corker skewered Donald Trump,Image copyright Getty Images\nOn Sunday mornin...,1
1,Linklater's war veteran comedy speaks to moder...,"LONDON (Reuters) - Last Flag Flying, a comed...",1
2,Trumps Fight With Corker Jeopardizes His Legi...,The feud broke into public view last week when...,1

In [81]:
file_1_nd_3 = z.combine_first(x)
file_1_nd_3

,label,news_url,source_domain,text,title,tweet_num
0,1,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,Image copyright Getty Images\nOn Sunday mornin...,Kandi Burruss Explodes Over Rape Accusation on...,42
1,1,https://www.today.com/style/see-people-s-choic...,www.today.com,"LONDON (Reuters) - Last Flag Flying, a comed...",People's Choice Awards 2018: The best red carp...,0
2,1,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,The feud broke into public view last week when...,Sophia Bush Sends Sweet Birthday Message to 'O...,63
3,1,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,MEXICO CITY (Reuters) - Egypts Cheiron Holdin...,Colombian singer Maluma sparks rumours of inap...,20
4,1,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,"Country singer Jason Aldean, who was performin...",Gossip Girl 10 Years Later: How Upper East Sid...,38
...,...,...,...,...,...,...
23191,1,https://www.express.co.uk/news/royal/807049/pi...,www.express.co.uk,NaN,Pippa Middleton wedding: In case you missed it...,52
23192,0,hollywoodlife.com/2018/03/13/zayn-malik-gigi-h...,hollywoodlife.com,NaN,Zayn Malik & Gigi Hadidâs Shocking Split: Wh...,7
23193,1,http://www.justjared.com/2018/01/17/jessica-ch...,www.justjared.com,NaN,Jessica Chastain Recalls the Moment Her Mother...,26
23194,0,www.intouchweekly.com/posts/tristan-thompson-f...,www.intouchweekly.com,NaN,"Tristan Thompson Feels ""Dumped"" After KhloÃ© K...",24
23195,1,https://www.billboard.com/articles/news/bbma/8...,www.billboard.com,NaN,Kelly Clarkson Performs a Medley of Kendrick L...,85

In [82]:
file_1_nd_3.fillna(file_1_nd_3['text'].mode()[0])

,label,news_url,source_domain,text,title,tweet_num
0,1,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,Image copyright Getty Images\nOn Sunday mornin...,Kandi Burruss Explodes Over Rape Accusation on...,42
1,1,https://www.today.com/style/see-people-s-choic...,www.today.com,"LONDON (Reuters) - Last Flag Flying, a comed...",People's Choice Awards 2018: The best red carp...,0
2,1,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,The feud broke into public view last week when...,Sophia Bush Sends Sweet Birthday Message to 'O...,63
3,1,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,MEXICO CITY (Reuters) - Egypts Cheiron Holdin...,Colombian singer Maluma sparks rumours of inap...,20
4,1,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,"Country singer Jason Aldean, who was performin...",Gossip Girl 10 Years Later: How Upper East Sid...,38
...,...,...,...,...,...,...
23191,1,https://www.express.co.uk/news/royal/807049/pi...,www.express.co.uk,A Potato Battery Can Light up a Room for Over ...,Pippa Middleton wedding: In case you missed it...,52
23192,0,hollywoodlife.com/2018/03/13/zayn-malik-gigi-h...,hollywoodlife.com,A Potato Battery Can Light up a Room for Over ...,Zayn Malik & Gigi Hadidâs Shocking Split: Wh...,7
23193,1,http://www.justjared.com/2018/01/17/jessica-ch...,www.justjared.com,A Potato Battery Can Light up a Room for Over ...,Jessica Chastain Recalls the Moment Her Mother...,26
23194,0,www.intouchweekly.com/posts/tristan-thompson-f...,www.intouchweekly.com,A Potato Battery Can Light up a Room for Over ...,"Tristan Thompson Feels ""Dumped"" After KhloÃ© K...",24
23195,1,https://www.billboard.com/articles/news/bbma/8...,www.billboard.com,A Potato Battery Can Light up a Room for Over ...,Kelly Clarkson Performs a Medley of Kendrick L...,85